blackB="$(tput setab 0)"
blackF="$(tput setaf 0)"
redB="$(tput setab 1)"
redF="$(tput setaf 1)"
greenB="$(tput setab 2)"
greenF="$(tput setaf 2)"
yellowB="$(tput setab 3)"
yellowF="$(tput setaf 3)"
blueB="$(tput setab 4)"
blueF="$(tput setaf 4)"
magentaB="$(tput setab 5)"
magentaF="$(tput setaf 5)"
cyanB="$(tput setab 6)"
cyanF="$(tput setaf 6)"
whiteB="$(tput setab 7)"
whiteF="$(tput setaf 7)"

